' Constantes globais

Public Const BROKER As String = "Broker"
Public Const RESERVA_ESTRATEGICA As String = "Reserva estratégica"

' Planilha Intro
Public Const RANGE_DATA_ULTIMA_ATUALIZ As String = "E12"
Public Const RANGE_POSICAO = "posicao"

' Planilha Orcamento
Public Const RANGE_TOLERANCIA As String = "tolerancia"
Public Const TIPO_LANCAMENTO_INVESTIMENTOS As String = "investimentos"

' Planilha Alocacao
Public Const RANGE_CELULA_INICIO_ADHOC As String = "C87"
Public Const RANGE_CELULA_FIM_ADHOC As String = "C91"
Public Const RANGE_CELULA_INICIO_PORTFOLIO As String = "C38"
Public Const RANGE_CELULA_FIM_PORTFOLIO As String = "C77"

' Planilha Retrato
Public Const RANGE_RELAT_RETRAT = "$A$1:$Q$108"

' Planilhas Jan. a Dez - geral
Public Const RANGE_SITUAC_PLANILHA As String = "E4"
Public Const RANGE_DATA_POSICAO As String = "N4"
Public Const SITUAC_ABERTO As String = "Aberto"
Public Const SITUAC_FECHADO As String = "Fechado"
Public Const RANGE_SALDO_MES As String = "B2"
Public Const NOME_PLAN_DEZ As String = "Dez"

' Planilhas Jan. a Dez - Conta corretora
Public Const RANGE_SALDO_CONTA_XP As String = "B22"
Public Const RANGE_SALDO_CONTA_AVENUE_USD_TOTAL As String = "B26"
Public Const RANGE_SALDO_CONTA_AVENUE_USD_DO_BRASIL As String = "B28"
Public Const RANGE_SALDO_CONTA_AVENUE_BR As String = "B30"

' Planilhas Jan. a Dez - movimentações
Public Const RANGE_HEADER_MOVIMENTACAO As String = "D14"
Public Const RANGE_HEADER_DATA_MOVIMENTACAO As String = "D15"
Public Const RANGE_PRIMEIRA_DATA_MOVIMENTACAO As String = "D16"
Public Const RANGE_HEADER_DESC_MOVIMENTACAO As String = "E15"
Public Const RANGE_HEADER_TIPO_MOVIMENTACAO As String = "F15"
Public Const RANGE_HEADER_VALOR_MOVIMENTACAO As String = "G15"
Public Const RANGE_COLUNA_DATA_MOVIMENTACAO As String = "D16:D66"
Public Const RANGE_COLUNA_VALOR_MOVIMENTACAO As String = "G16:G66"
Public Const RANGE_TAB_MOVIMENTACAO As String = "D16:G66"

' Planilhas Jan. a Dez - cartões
Public Const RANGE_COLUNA_VALOR_CARTOES As String = "N16:N66"
Public Const RANGE_ULTIMO_VALOR_CARTAO As String = "N66"
Public Const RANGE_HEADER_CARTOES As String = "J14"
Public Const RANGE_PRIMEIRA_DATA_CARTOES As String = "J16"
Public Const RANGE_COLUNA_DATA_CARTOES As String = "J16:J66"
Public Const RANGE_TAB_CARTOES As String = "J16:N66"

' Portfólio
Public Const RANGE_COLUNA_ATIVO_PORTFOLIO As String = "D74:D112"
Public Const RANGE_COLUNA_SALDO_INICIAL_PORTFOLIO As String = "F74:F112"
Public Const RANGE_COLUNA_SALDO_FINAL_PORTFOLIO As String = "N74:N112"

Public Const RANGE_AREA_RELATORIO As String = "C72:N115"

' Carteira Ações
Public Const RANGE_COLUNA_DATA_ACOES As String = "D117:D146"
Public Const RANGE_COLUNA_ATIVO_ACOES As String = "E117:E146"
Public Const RANGE_COLUNA_QTDE_ACOES As String = "G117:G146"
Public Const RANGE_COLUNA_SALDO_INICIAL_ACOES As String = "F117:F146"
Public Const RANGE_COLUNA_SALDO_FINAL_ACOES As String = "N117:N146"
Public Const RANGE_COLUNA_CUSTO_MEDIO_ACOES As String = "S117:S146"
Public Const RANGE_CELULA_TRIBUTAL_ACOES As String = "Q147"
Public Const RANGE_COLUNA_RESULTADO_COMUM_ACOES As String = "W117:W146"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_ACOES As String = "AA117:AA146"

' Carteira Fundos Imobiliários
Public Const RANGE_COLUNA_DATA_FII As String = "D153:D182"
Public Const RANGE_COLUNA_ATIVO_FII As String = "E153:E182"
Public Const RANGE_COLUNA_QTDE_FII As String = "G153:G182"
Public Const RANGE_COLUNA_SALDO_INICIAL_FII As String = "F153:F182"
Public Const RANGE_COLUNA_SALDO_FINAL_FII As String = "N153:N182"
Public Const RANGE_COLUNA_CUSTO_MEDIO_FII As String = "S153:S182"
Public Const RANGE_COLUNA_RESULTADO_COMUM_FII As String = "W153:W182"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_FII As String = "AA153:AA182"

' Carteira Tesouro Direto RF
Public Const RANGE_COLUNA_DATA_TESOURO_DIRETO As String = "D189:D203"
Public Const RANGE_COLUNA_ATIVO_TESOURO_DIRETO As String = "E189:E203"
Public Const RANGE_COLUNA_QTDE_TESOURO_DIRETO As String = "G189:G203"
Public Const RANGE_COLUNA_SALDO_INICIAL_TESOURO_DIRETO As String = "F189:F203"
Public Const RANGE_COLUNA_SALDO_FINAL_TESOURO_DIRETO As String = "N189:N203"

' Carteira Tesouro Direto Selic
Public Const RANGE_COLUNA_DATA_TESOURO_SELIC As String = "D210:D215"
Public Const RANGE_COLUNA_ATIVO_TESOURO_SELIC As String = "E210:E215"
Public Const RANGE_COLUNA_QTDE_TESOURO_SELIC As String = "G210:G215"
Public Const RANGE_COLUNA_SALDO_INICIAL_TESOURO_SELIC As String = "F210:F215"
Public Const RANGE_COLUNA_SALDO_FINAL_TESOURO_SELIC As String = "N210:N215"

' Carteira ETF BR
Public Const RANGE_COLUNA_DATA_ETFBR As String = "D222:D228"
Public Const RANGE_COLUNA_ATIVO_ETFBR As String = "E222:E228"
Public Const RANGE_COLUNA_QTDE_ETFBR As String = "G222:G228"
Public Const RANGE_COLUNA_SALDO_INICIAL_ETFBR As String = "F222:F228"
Public Const RANGE_COLUNA_SALDO_FINAL_ETFBR As String = "N222:N228"
Public Const RANGE_COLUNA_CUSTO_MEDIO_ETFBR As String = "S222:S228"
Public Const RANGE_COLUNA_RESULTADO_COMUM_ETFBR As String = "W222:W228"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_ETFBR As String = "AA222:AA228"

' Carteira ETF USD
Public Const RANGE_COLUNA_DATA_ETFUSD As String = "D235:D241"
Public Const RANGE_COLUNA_ATIVO_ETFUSD As String = "E235:E241"
Public Const RANGE_COLUNA_QTDE_ETFUSD As String = "G235:G241"
Public Const RANGE_COLUNA_SALDO_INICIAL_ETFUSD As String = "F235:F241"
Public Const RANGE_COLUNA_SALDO_FINAL_ETFUSD As String = "N235:N241"
Public Const RANGE_COLUNA_CUSTO_MEDIO_ETFUSD As String = "S235:S241"
Public Const RANGE_COLUNA_RESULTADO_COMUM_ETFUSD As String = "W235:W241"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_ETFUSD As String = "AA235:AA241"

' Carteira Ações USD
Public Const RANGE_COLUNA_DATA_STOCK As String = "D248:D277"
Public Const RANGE_COLUNA_ATIVO_STOCK As String = "E248:E277"
Public Const RANGE_COLUNA_QTDE_STOCK As String = "G248:G277"
Public Const RANGE_COLUNA_SALDO_INICIAL_STOCK As String = "F248:F277"
Public Const RANGE_COLUNA_SALDO_FINAL_STOCK As String = "N248:N277"
Public Const RANGE_COLUNA_CUSTO_MEDIO_STOCK As String = "S248:S277"
Public Const RANGE_CELULA_TRIBUTAL_STOCK As String = "Q278"
Public Const RANGE_COLUNA_RESULTADO_COMUM_STOCK As String = "W248:W277"

' Carteira REIT
Public Const RANGE_COLUNA_DATA_REIT As String = "D284:D313"
Public Const RANGE_COLUNA_ATIVO_REIT As String = "E284:E313"
Public Const RANGE_COLUNA_QTDE_REIT As String = "G284:G313"
Public Const RANGE_COLUNA_SALDO_INICIAL_REIT As String = "F284:F313"
Public Const RANGE_COLUNA_SALDO_FINAL_REIT As String = "N284:N313"
Public Const RANGE_COLUNA_CUSTO_MEDIO_REIT As String = "S284:S313"
Public Const RANGE_CELULA_TRIBUTAL_REIT As String = "Q314"
Public Const RANGE_COLUNA_RESULTADO_COMUM_REIT As String = "W284:W313"

' Carteira Treasuries
Public Const RANGE_COLUNA_DATA_CART_TREASURY As String = "D320:D329"
Public Const RANGE_COLUNA_ATIVO_CART_TREASURY As String = "E320:E329"
Public Const RANGE_COLUNA_QTDE_CART_TREASURY As String = "G320:G329"
Public Const RANGE_COLUNA_SALDO_INICIAL_CART_TREASURY As String = "F320:F329"
Public Const RANGE_COLUNA_SALDO_FINAL_CART_TREASURY As String = "N320:N329"
Public Const RANGE_COLUNA_CUSTO_MEDIO_CART_TREASURY As String = "S320:S329"
Public Const RANGE_COLUNA_RESULTADO_COMUM_TREASURY As String = "W320:W329"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_TREASURY As String = "AA320:AA329"

' Carteira Commodity
Public Const RANGE_COLUNA_DATA_COMMODITY As String = "D336:D345"
Public Const RANGE_COLUNA_ATIVO_COMMODITY As String = "E336:E345"
Public Const RANGE_COLUNA_QTDE_COMMODITY As String = "G336:G345"
Public Const RANGE_COLUNA_SALDO_INICIAL_COMMODITY As String = "F336:F345"
Public Const RANGE_COLUNA_SALDO_FINAL_COMMODITY As String = "N336:N345"
Public Const RANGE_COLUNA_CUSTO_MEDIO_COMMODITY As String = "S336:S345"
Public Const RANGE_COLUNA_RESULTADO_COMUM_COMMODITY As String = "W336:W345"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_COMMODITY As String = "AA336:AA345"

' Carteira Opções
Public Const RANGE_COLUNA_DATA_OPCOES As String = "D352:D361"
Public Const RANGE_COLUNA_ATIVO_OPCOES As String = "E352:E361"
Public Const RANGE_COLUNA_QTDE_OPCOES As String = "G352:G361"
Public Const RANGE_COLUNA_SALDO_INICIAL_OPCOES As String = "F352:F361"
Public Const RANGE_COLUNA_SALDO_FINAL_OPCOES As String = "N352:N361"
Public Const RANGE_COLUNA_CUSTO_MEDIO_OPCOES As String = "S352:S361"
Public Const RANGE_COLUNA_RESULTADO_COMUM_OPCOES As String = "W352:W361"
Public Const RANGE_COLUNA_RESULTADO_DAYTRADE_OPCOES As String = "AA352:AA361"

' Planilhas Jan. a Dez - indicadores
Public Const RANGE_COLUNA_DESCR_INDICADORES As String = "D371:D380"
Public Const RANGE_COLUNA_MES_INDICADORES As String = "F371:F380"
Public Const RANGE_COLUNA_ANO_INDICADORES As String = "H371:H380"
Public Const RANGE_COLUNA_DOZE_MESES_INDICADORES As String = "I371:I380"
Public Const RANGE_CELULA_DOLAR_FINAL_MES As String = "G377"
Public Const SP500 As String = "S&P 500"

